FROM golang:1.8.3 AS build

ARG version=dev
ARG package=github.com/tuenti/pouch

ENV GOPATH /gopath
ENV SRC $GOPATH/src/$package

WORKDIR $SRC
COPY . $SRC
RUN go install -ldflags "-X main.version=$version" $package/cmd/approle-login

FROM alpine:3.6
RUN apk update && apk add libc6-compat && rm -f /var/cache/apk/*
COPY --from=build /gopath/bin/approle-login /usr/bin/
CMD /usr/bin/approle-login
